--协议映射表，协议名->{proto类型(请求/响应，广播)}
local proto_map = {
    login_first = { req = "game.LoginFirstReq", res = "game.LoginFirstRes" },
    login_second = { req = "game.LoginSecondReq", res = "game.LoginSecondRes" },
    register = { req = "game.RegisterReq", res = "game.RegisterRes" },
    kick = { notify = "game.KickNotify" },
    enter = { req = "game.EnterReq", res = "game.EnterRes" },
    leave = { req = "game.LeaveReq", res = "game.LeaveRes" },
    input_frame = { req = "game.InputFrameReq" },
    frame_update = { notify = "game.FrameUpdate" },
    scene_snapshot = { notify = "game.SceneSnapshot" },
    enter_notify = { notify = "game.EnterNotify" },
    leave_notify = { notify = "game.LeaveNotify" },

    achieve_list = { req = "game.AchieveListReq", res = "game.AchieveListRes" },
    achieve_claim = { req = "game.AchieveClaimReq", res = "game.AchieveClaimRes" },
    achieve_notify = { notify = "game.AchieveNotify" },
    work = { req = "game.WorkReq", res = "game.WorkRes" },
    baglist = { req = "game.BagListReq", res = "game.BagListRes" },
    use_item = { req = "game.UseItemReq", res = "game.UseItemRes" },
    mail_list = { req = "game.MailListReq", res = "game.MailListRes" },
    mail_read = { req = "game.MailReadReq", res = "game.MailReadRes" },
    mail_claim = { req = "game.MailClaimReq", res = "game.MailClaimRes" },
    mail_delete = { req = "game.MailDeleteReq", res = "game.MailDeleteRes" },
    mail_notify = { notify = "game.MailNotify" },
    friend_list = { req = "game.FriendListReq", res = "game.FriendListRes" },
    friend_info = { req = "game.FriendInfoReq", res = "game.FriendInfoRes" },
    friend_pending_list = { req = "game.FriendPendingReq", res = "game.FriendPendingRes" },
    friend_add = { req = "game.FriendAddReq", res = "game.FriendAddRes" },
    friend_accept = { req = "game.FriendAcceptReq", res = "game.FriendAcceptRes" },
    friend_delete = { req = "game.FriendDeleteReq", res = "game.FriendDeleteRes" },
    friend_reject = { req = "game.FriendRejectReq", res = "game.FriendRejectRes" },
    base_info = { req = "game.BaseInfoReq", res = "game.BaseInfoRes" },
    reconnect = { req = "game.ReconnectReq", res = "game.ReconnectRes" },
    battle_auth = { req = "game.BattleAuthReq", res = "game.BattleAuthRes" },
    battle_ready_ack = { req = "game.BattleReadyAckReq" },
    join_match = { req = "game.JoinMatchReq", res = "game.JoinMatchRes" },
    cancel_match = { req = "game.CancelMatchReq", res = "game.CancelMatchRes" },
    match_status = { req = "game.MatchStatusReq", res = "game.MatchStatusRes" },
    match_found = { notify = "game.MatchFoundNotify" },
    prepare = { req = "game.PrepareReq", res = "game.PrepareRes" },
    room_prepare = { notify = "game.RoomPrepareNotify" },
    battle_connect = { notify = "game.BattleConnectNotify" },
    room_dismiss = { notify = "game.RoomDismissNotify" },
    battle_result = { notify = "game.BattleResultNotify" },
}

return proto_map
